# Generated by Django 4.1.3 on 2022-12-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podpischiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('session_id', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'заявки',
            },
        ),
    ]
